spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /api/ping
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 5

