spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /check
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5


